### PR TITLE
:family: How to deal with PRs in shared repos

### PR DESCRIPTION
**Pull request by st3v3nhunt**

### CODE REVIEW

**Comment by Demotive** [comment]
That makes sense to me. It might slow us down a bit, but I do think the idea of it being people from different build teams is a good one.

Should we assign people to our PRs in shared repos like this? At least while the team is small...

**Comment by st3v3nhunt** [comment]
The assigning question is an interesting one. In the recent past I have been working in a way where the first person to get to the PR assigns themselves rather than the author doing the assigning.

This can lead to nobody looking at the PR (which I didn't experience) and can be mitigated by the author actively seeking reviewers.

**Comment by teneightfive** [comment]
Yeah, assigning is also limited to 1 person with github PRs so might seem like they are the only ones responsible for reviewing it. 

I've used labels in the past to signify it's state. Things like 'for review' when you want feedback or 'do not merge' if it's not ready to be merged. You might be creating a PR to build an instance of that code on heroku for example.

**Comment by Demotive** [comment]
Discussion around "assign" can move to a different channel? Content of this PR looks good, gonna merge.

**Pull request merged**
